### ISSUE TITLE
This is going to break on some builtins like str()

### ISSUE THREAD

**Issue by Niriel** [Niriel/yummycurry#2]
Calling inspect.signature(str) explodes, for some reason str has no signature.  We need to be ready for that.

**Comment by sobolevn** [comment]
For some reason this works for `toolz.curry` which uses `inspect.signature` as well: https://github.com/pytoolz/toolz/blob/ea3ba0d60a33b256c8b2a7be43aff926992ffcdb/toolz/functoolz.py#L234

Current problem:

```
>>> yummycurry.curry(int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.8/site-packages/yummycurry/curry.py", line 157, in curry
    return _curry(f, args, kwargs)
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.8/site-packages/yummycurry/curry.py", line 118, in _curry
    sig = inspect.signature(f)
  File "/Users/sobolev/.pyenv/versions/3.8.0/lib/python3.8/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/Users/sobolev/.pyenv/versions/3.8.0/lib/python3.8/inspect.py", line 2842, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/Users/sobolev/.pyenv/versions/3.8.0/lib/python3.8/inspect.py", line 2372, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'int'>
```

Example from `toolz`:

```
>>> toolz.curry(str)
<class 'str'>
```

**Comment by Niriel** [comment]
I'll dig into it. It's starting to seriously annoy me as well. I'll have a look at what `toolz` does to avoid this problem.
